@echo off
echo Running Black formatting...
python -m black --line-length 100 src/ tests/
echo Running Flake8 linting...
python -m flake8 src/ tests/
echo Running Pylint analysis...
python -m pylint src/fortherekord
echo Running MyPy type checking...
python -m mypy src/fortherekord
