name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*', '[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Required for creating releases
  actions: read    # Required for downloading artifacts

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-13  # Intel runner (more stable than macos-latest)
            platform: macos
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Build executable
      run: python compile.py
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fortherekord-${{ matrix.platform }}
        path: dist/
        retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: fortherekord-windows
        path: windows-dist/
        
    - name: Download macOS artifacts  
      uses: actions/download-artifact@v4
      with:
        name: fortherekord-macos
        path: macos-dist/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-dist/fortherekord-windows.exe
          macos-dist/fortherekord-macos
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}